site_name: Interrailinfo på svenska - testversion
site_description: "Spåret till #Tågskryt"
site_url: https://test.trainfo.eu

theme:
  name: material
  logo: images/icon.png
  features:
    - header.autohide
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  
plugins:
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date
  - tags:
      tags_allowed:
        - Belgien
        - Danmark
        - Finland
        - Frankrike
        - Holland
        - Interrail
        - Italien
        - London
        - nattåg
        - Norge
        - Polen
        - Portugal
        - Rese-exempel
        - Spanien
        - Sverige
        - Tjeckien
        - Tyskland
        - Ukraina
        - planering
        - platsbiljett
        - "praktisk info"
        - railplanner
        - reseberättelser
        - sajten
        - tips
        - "under resan"
        - Österrike
  - blog:
  - search

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodonsweden.se/@interrailinfosvenska
      name: Mastodon
    - icon: fontawesome/solid/envelope
      link: mailto:interrailinfosvenska@protonmail.com

extra_javascript:
  - stat_counter.js