site_name: Interrailinfo på svenska
site_description: "Spåret till #Tågskryt"
site_url: https://test.trainfo.eu

theme:
  name: material
  logo: images/icon.png
  
plugins:
  - rss:
      match_path: "blog/.*"
      feed_ttl: 1
  - tags:
      tags_file: tags.md
  - blog:
      use_git: false
  - social:
      cards: false
  - search

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodonsweden.se/@interrailinfosvenska
      name: Mastodon


